#standard import
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import warnings
import seaborn as sns
warnings.filterwarnings('ignore')
import psycopg2
import logging
import sys
import time
from typing import Dict, List
import re
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from collections import Counter
from pathlib import Path

class PotentialCustomersClassifier:
    def __init__(self, db_params):
        self.__db_params = db_params
        self.__setup_logging()

    def __setup_logging(self):
        logging.basicConfig(
            level=logging.INFO,
            format='%(asctime)s - %(levelname)s - %(message)s',
            handlers=[
                logging.FileHandler('customer_finder.log'),
                logging.StreamHandler(sys.stdout)
            ]
        )
        self.logger = logging.getLogger(__name__)

    def retrieve_raw_data(self) -> pd.DataFrame:
        try:
            conn = psycopg2.connect(**self.__db_params)
            cur = conn.cursor()
            cur.execute("""
            SELECT general_businesses.id AS business_id,
                business_act.act_code AS act_code,
                activities.descr AS act_descr,
                general_businesses.auth_capital AS auth_capital
            FROM general_businesses
                JOIN industrial_parks 
                    ON general_businesses.park_id = industrial_parks.id
                JOIN business_act 
                    ON general_businesses.id = business_act.business_id
                JOIN activities 
                    ON business_act.act_code = activities.code
            WHERE business_act.main_act = true
            """)
            df = pd.DataFrame(cur.fetchall())
            df.columns = ["business_id", "act_code", "act_descr", "auth_cap"]
            self.logger.info("Finished getting raw data")
            return df
        except Exception as e:
            conn.rollback()
            self.logger.error(str(e))
            raise
        finally:
            if conn:
                cur.close()
                conn.close()
    
    def export_to_(self, f_format: str|None ='csv' ) -> None:
        export_f = {
            'csv': pd.DataFrame.to_csv,
            'xlsx': pd.DataFrame.to_excel
        }
        try:
            raw_data = self.retrieve_raw_data()
            out_path = Path.cwd() / f"customers_raw_.{f_format}"
            export_f[f_format](raw_data, out_path, index=False)
        except Exception as e:
            self.logger.error(e)
            raise
    
    def create_model_(self):
        ...

    def plot_data(self, df: pd.DataFrame):
        xArray = df['business_id']
        yArray = df['auth_cap']
        plt.plot(xArray, yArray, marker='^', ls='')
        plt.show()

def main():
    db_param = {
        'host': 'localhost',
        'database': 'businessesdb',
        'user': 'postgres',
        'password': '1234',
        'port': '5432'
    }
    try:
        custClass = PotentialCustomersClassifier(db_params=db_param)
        custClass.export_to_()
        custClass.plot_data(custClass.retrieve_raw_data())

    except Exception as e:
        print(str(e))

if __name__ == "__main__":
    main()